version: '3.6'
services:
  webserver:
    image: egurnick/django-graphql-quickstart
    build: .
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"

